server:
  port: 8081
spring:
  profiles:
    active: dev #切换不同环境的配置信息
  aop:
    proxy-target-class: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  redis:
    host: localhost
    port: 6379
    password: pwd123456
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 20
        # 最大空闲连接数 默认8
        max-idle: 10
        # 最小空闲连接数 默认0
        min-idle: 2
        max-wait: 10000

mybatis:
  mapperLocations: classpath*:mapper/*Dao.xml
  typeAliasesPackage: com.crawl.tohoku.entity

proxy.page.proxy.queueName: tohoku-proxy-page-proxy-list
target.page.proxy.queueName: tohoku-page-proxy-list